# Generated by Django 4.1.5 on 2023-01-20 09:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heal', '0002_accounts_account_name_alter_accounts_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='account_number',
            field=models.BigIntegerField(validators=[django.core.validators.RegexValidator('^\\d{10}$', 'Enter a valid 10 digit account number.')]),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
