# Generated by Django 4.1.5 on 2023-01-20 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('heal', '0004_users_user_identity_users_user_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insuranceproducts',
            old_name='name',
            new_name='coverage',
        ),
        migrations.RemoveField(
            model_name='insuranceproducts',
            name='description',
        ),
        migrations.AddField(
            model_name='insuranceproducts',
            name='product_name',
            field=models.CharField(default='unknown', max_length=200),
        ),
        migrations.AddField(
            model_name='insuranceproducts',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='heal.users'),
        ),
    ]
