# Generated by Django 4.1.5 on 2023-01-20 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heal', '0005_rename_name_insuranceproducts_coverage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insuranceproducts',
            name='user',
        ),
    ]
