# Generated by Django 4.1.5 on 2023-01-20 15:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heal', '0006_remove_insuranceproducts_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='user_Identity',
            field=models.BigIntegerField(validators=[django.core.validators.RegexValidator('^\\d{14}$', 'Enter a valid 14 digit account number.')]),
        ),
    ]
