# Generated by Django 4.1.5 on 2023-01-22 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heal', '0007_alter_users_user_identity'),
    ]

    operations = [
        migrations.AddField(
            model_name='recives',
            name='recive_number',
            field=models.CharField(default='R0000', max_length=255),
        ),
    ]
