# Generated by Django 4.1.5 on 2023-01-22 04:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('heal', '0008_recives_recive_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recives',
            name='recive_number',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=36),
        ),
    ]
