# Generated by Django 4.1.5 on 2023-01-22 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heal', '0009_alter_recives_recive_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accounts',
            old_name='user',
            new_name='user_name',
        ),
    ]
