# Generated by Django 4.1.5 on 2023-01-23 05:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('heal', '0010_rename_user_accounts_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='recives',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
