# Generated by Django 4.1.5 on 2023-01-23 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heal', '0011_recives_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuranceproducts',
            name='photo_url',
            field=models.TextField(default='unknown'),
        ),
    ]
