# Generated by Django 4.1.5 on 2023-01-26 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('heal', '0013_alter_accounts_user_name_alter_recives_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='user_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL),
        ),
    ]
