# Generated by Django 4.1.5 on 2023-01-26 12:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_Identity',
            field=models.BigIntegerField(null=True, validators=[django.core.validators.RegexValidator('^\\d{14}$', 'Enter a valid 14 digit account number.')]),
        ),
    ]
